<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "extension_skeleton"
 *
 * Auto generated by Extension Builder 2018-05-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['extension_skeleton'] = [
    'title' => 'Extbase Skeleton - Frontend Plugin',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christian Hackl',
    'author_email' => 'hackl.chris@googlemail.com',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.99',
            'fluid_styled_content' => '10.4.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
